// Generated by scripts/generate-guide-translations.mjs.
import { guideTranslationsPart1 } from './guide-translations.generated.part1.ts';
import { guideTranslationsPart2 } from './guide-translations.generated.part2.ts';

export const guideTranslations = { ...guideTranslationsPart1, ...guideTranslationsPart2 } as const;
