const ORIGIN='https://kakobuymake.com';
const PAGE=__PAGE__;
const SITE='https://hipobuysheetnotes.com';
function decode(s=''){return s.replace(/&(?:amp|quot|#39|lt|gt|nbsp);|&#(?:x[0-9a-f]+|\d+);/gi,m=>{const named={'&amp;':'&','&quot;':'"','&#39;':"'",'&lt;':'<','&gt;':'>','&nbsp;':' '};if(named[m.toLowerCase()])return named[m.toLowerCase()];const n=m.startsWith('&#x')?parseInt(m.slice(3,-1),16):parseInt(m.slice(2,-1),10);return Number.isFinite(n)?String.fromCodePoint(n):m})}
function text(s=''){return decode(s.replace(/<[^>]*>/g,'').trim())}
function capture(s,re){return s.match(re)?.[1]||''}
function img(s){const path=decode(s);try{const u=new URL(path,ORIGIN);return u.origin===ORIGIN&&u.pathname.startsWith('/uploads/')?u.href:''}catch{return ''}}
async function source(url){const ctrl=new AbortController();const timer=setTimeout(()=>ctrl.abort(),20000);try{const r=await fetch(url,{headers:{'Accept':'text/html','User-Agent':'Mozilla/5.0 (compatible; SheetNotes/1.0)'},signal:ctrl.signal});if(!r.ok)throw new Error('Source '+r.status);const html=await r.text();if(html.length>3000000)throw new Error('Source too large');return html}finally{clearTimeout(timer)}}
function categories(html){const found=new Map();for(const m of html.matchAll(/<a\b[^>]*href="[^"]*[?&]tid=(\d+)[^"]*"[^>]*class="filter-option[^"]*"[^>]*>([\s\S]*?)<\/a>/gi)){const id=Number(m[1]);const name=text(m[2]);if(id>1&&id<1000&&name)found.set(id,{id,name})}return [...found.values()]}
function products(html){const found=new Map();for(const m of html.matchAll(/<a\b[^>]*href="[^"]*[?&]aid=(\d+)[^"]*"[^>]*class="product-card[^"]*"[^>]*>([\s\S]*?)<\/a>/gi)){const id=m[1],block=m[2];const title=text(capture(block,/<h3\b[^>]*class="product-title"[^>]*>([\s\S]*?)<\/h3>/i));const image=img(capture(block,/<img\b[^>]*data-src="([^"]+)"/i)||capture(block,/<img\b[^>]*src="([^"]+)"/i));const price=text(capture(block,/<span\b[^>]*class="price"[^>]*>([\s\S]*?)<\/span>/i));if(id&&title&&image)found.set(id,{id,title,image,price,sourceUrl:`${ORIGIN}/?m=home&c=View&a=index&aid=${id}`})}return [...found.values()]}
function pagination(html){const match=html.match(/共\s*<strong>(\d+)<\/strong>\s*页\s*<strong>(\d+)<\/strong>\s*条/i);return {totalPages:match?Number(match[1]):0,totalItems:match?Number(match[2]):0}}
function purchase(html){for(const m of html.matchAll(/<a\b[^>]*href="([^"]+)"[^>]*>/gi)){try{const u=new URL(decode(m[1]));if(u.origin==='https://hipobuy.com'&&/^\/product\/weidian\/\d+$/.test(u.pathname)&&u.searchParams.get('inviteCode')==='7INJEO667'&&[...u.searchParams.keys()].every(k=>k==='inviteCode'))return u.href}catch{}}return ''}
function hipobuyImage(value){if(typeof value!=='string')return '';try{const url=new URL(value);return url.protocol==='https:'&&url.hostname==='si.geilicdn.com'?url.href:''}catch{return ''}}
async function sellerImages(buy,fallback){const failed={images:[fallback],galleryStatus:'unavailable'};const itemId=buy.match(/^https:\/\/hipobuy\.com\/product\/weidian\/(\d{1,15})\?/)?.[1];if(!itemId)return {images:[fallback],galleryStatus:'missing-id'};const url=new URL('https://weidian.com/item.html');url.searchParams.set('itemID',itemId);try{const response=await fetch(url,{headers:{Accept:'text/html','User-Agent':'Mozilla/5.0 (compatible; SheetNotes/1.0)'},signal:AbortSignal.timeout(15000)});if(!response.ok)return failed;const html=await response.text();if(html.length>2000000)return failed;const encoded=html.match(/<script\b[^>]*id="__rocker-render-inject__"[^>]*data-obj="([^"]+)"/i)?.[1];if(!encoded)return failed;const model=JSON.parse(decode(encoded))?.result?.default_model,item=model?.item_info;if(String(item?.item_id)!==itemId||!Array.isArray(item?.imgs))return failed;const primary=item.imgs.map(hipobuyImage).filter((src,index,list)=>src&&list.indexOf(src)===index);if(primary.length>1)return {images:primary.slice(0,60),galleryStatus:'seller'};const sku=model?.sku_properties||{};const variantValues=(Array.isArray(sku.attr_list)?sku.attr_list:[]).flatMap(group=>Array.isArray(group?.attr_values)?group.attr_values.map(value=>value?.img):[]);const skuValues=Object.values(sku.sku||{}).map(value=>value?.img);const images=[...primary,...variantValues,...skuValues].map(hipobuyImage).filter((src,index,list)=>src&&list.indexOf(src)===index).slice(0,60);return images.length?{images,galleryStatus:images.length>primary.length?'seller-variants':'seller'}:failed}catch{return failed}}
function qcImages(html){const found=[];for(const block of html.matchAll(/<(?:section|div)\b[^>]*(?:id|class)="[^"]*(?:qc[-_ ]?(?:photos|gallery)|quality[-_ ]?control)[^"]*"[^>]*>([\s\S]*?)<\/(?:section|div)>/gi)){for(const match of block[1].matchAll(/<img\b[^>]*(?:data-src|src)="([^"]+)"/gi)){const url=img(match[1]);if(url&&!found.includes(url))found.push(url)}}return found}
function detail(html,id){const title=text(capture(html,/<h1\b[^>]*class="product-title"[^>]*>([\s\S]*?)<\/h1>/i));const main=img(capture(html,/<img\b[^>]*id="mainImage"[^>]*src="([^"]+)"/i));const gallery=capture(html,/<div\b[^>]*class="thumbnail-carousel"[^>]*>([\s\S]*?)<\/div>/i);const sourcePhotos=[main,...[...gallery.matchAll(/<img\b[^>]*src="([^"]+)"/gi)].map(x=>img(x[1]))].filter((x,i,a)=>x&&a.indexOf(x)===i);if(!title||!main)throw new Error('Missing product');const explicitQc=qcImages(html);const qcPhotos=explicitQc.length?explicitQc:sourcePhotos.filter(src=>src!==main);return {id,title,image:main,images:[main],buy:purchase(html),qcPhotos,qcStatus:explicitQc.length?'verified':'source-gallery',sourceUrl:`${ORIGIN}/?m=home&c=View&a=index&aid=${id}`,price:text(capture(html,/<span\b[^>]*class="current-price price"[^>]*>([\s\S]*?)<\/span>/i))}}
const json=(data,status=200)=>Response.json(data,{status,headers:{'cache-control':status===200?'public, max-age=120':'no-store','x-content-type-options':'nosniff'}});
const CURRENCIES=new Set(['USD','BRL','CNY','DKK','EUR','MXN','NZD','NOK','PLN','SEK','CHF','KRW','AUD','GBP','CAD']);
const xmlEscape=value=>String(value).replace(/[<>&"']/g,ch=>({'<':'&lt;','>':'&gt;','&':'&amp;','"':'&quot;',"'":'&apos;'}[ch]));
const xmlResponse=body=>new Response('<?xml version="1.0" encoding="UTF-8"?>\n'+body,{headers:{'content-type':'application/xml; charset=utf-8','cache-control':'public, max-age=3600','x-content-type-options':'nosniff'}});
const urlset=paths=>xmlResponse('<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'+[...new Set(paths)].map(path=>'<url><loc>'+xmlEscape(SITE+path)+'</loc></url>').join('')+'</urlset>');
export default {async fetch(request){const u=new URL(request.url);
if(u.pathname==='/robots.txt')return new Response('User-agent: *\nAllow: /\nDisallow: /api/\nSitemap: '+SITE+'/sitemap.xml\n',{headers:{'content-type':'text/plain; charset=utf-8','cache-control':'public, max-age=3600'}});
if(u.pathname==='/sitemap.xml'||u.pathname==='/sitemaps/pages.xml'||/^\/sitemaps\/products-[1-9]\d{0,2}\.xml$/.test(u.pathname)){
  const match=u.pathname.match(/products-(\d+)\.xml$/),page=match?Number(match[1]):1;
  const target=new URL(ORIGIN);if(page>1)target.searchParams.set('page',String(page));
  try{
    const html=await source(target),info=pagination(html);
    if(u.pathname==='/sitemap.xml')return xmlResponse('<sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'+['/sitemaps/pages.xml',...Array.from({length:Math.max(1,Math.min(info.totalPages||1,999))},(_,i)=>'/sitemaps/products-'+(i+1)+'.xml')].map(path=>'<sitemap><loc>'+SITE+path+'</loc></sitemap>').join('')+'</sitemapindex>');
    if(u.pathname==='/sitemaps/pages.xml')return urlset(['/', '/products','/categories',...categories(html).map(cat=>'/category/'+cat.id)]);
    if(info.totalPages&&page>info.totalPages)return new Response('Not found',{status:404});
    return urlset(products(html).map(item=>'/product/'+item.id));
  }catch(e){console.error('sitemap upstream:',e?.message);return new Response('Sitemap source temporarily unavailable',{status:503,headers:{'retry-after':'300','cache-control':'no-store'}})}
}
if(['/', '/products', '/categories'].includes(u.pathname)||/^\/category\/[1-9]\d{0,2}$/.test(u.pathname)||/^\/product\/[1-9]\d{0,9}$/.test(u.pathname)){return new Response(PAGE.replace("__CANONICAL_URL__",SITE+u.pathname),{headers:{'content-type':'text/html; charset=utf-8','cache-control':'no-store'}})}
if(u.pathname==='/api/rate'){
  const currency=u.searchParams.get('currency')||'USD';
  if(!CURRENCIES.has(currency))return json({error:'Unsupported currency'},400);
  if(currency==='USD')return new Response(JSON.stringify({currency,rate:1,date:new Date().toISOString().slice(0,10),source:'USD'}),{headers:{'content-type':'application/json','cache-control':'public, max-age=3600'}});
  try{
    const target=new URL('https://api.frankfurter.dev/v1/latest');target.searchParams.set('base','USD');target.searchParams.set('symbols',currency);
    const response=await fetch(target,{headers:{Accept:'application/json'},signal:AbortSignal.timeout(9000)});
    if(!response.ok)throw new Error('Exchange source unavailable');
    const data=await response.json(),rate=data?.rates?.[currency];
    if(data?.base!=='USD'||!Number.isFinite(rate)||rate<=0||rate>100000||!/^\d{4}-\d{2}-\d{2}$/.test(data?.date||''))throw new Error('Invalid exchange rate');
    return new Response(JSON.stringify({currency,rate,date:data.date,source:'Frankfurter'}),{headers:{'content-type':'application/json','cache-control':'public, max-age=14400','x-content-type-options':'nosniff'}});
  }catch(e){console.error('rate upstream:',e?.message);return json({error:'Exchange rate unavailable'},503)}
}
if(u.pathname==='/api/catalog'){const q=(u.searchParams.get('q')||'').trim().slice(0,100);const category=Number(u.searchParams.get('category')||0);const page=Number(u.searchParams.get('page')||1);const sort=u.searchParams.get('sort')||'';const sortMap={newest:['new','desc'],price_asc:['price','asc'],price_desc:['price','desc'],views:['click','desc']};if(sort&&(!Object.hasOwn(sortMap,sort)||q))return json({error:'Unsupported sort'},400);if(category&&(!Number.isInteger(category)||category<1||category>999))return json({error:'Invalid category'},400);if(!Number.isInteger(page)||page<1||page>1000)return json({error:'Invalid page'},400);const target=new URL(ORIGIN);target.searchParams.set('m','home');target.searchParams.set('c',q?'Search':category?'Lists':'Index');target.searchParams.set('a',q?'lists':'index');if(q){target.searchParams.set('keywords',q);target.searchParams.set('method','1');target.searchParams.set('channelid','2')}if(category)target.searchParams.set('tid',String(category));if(sort){target.searchParams.set('sort',sortMap[sort][0]);target.searchParams.set('sort_asc',sortMap[sort][1])}if(page>1)target.searchParams.set('page',String(page));try{const html=await source(target);const cats=categories(html);return json({categories:cats,products:products(html),page,sort,...pagination(html),fetchedAt:new Date().toISOString()})}catch(e){console.error('catalog upstream:',e?.name,e?.message);return json({error:'Source unavailable'},502)}}
if(u.pathname==='/api/detail'){const id=u.searchParams.get('id')||'';if(!/^[1-9]\d{0,9}$/.test(id))return json({error:'Invalid product ID'},400);try{const item=detail(await source(`${ORIGIN}/?m=home&c=View&a=index&aid=${id}`),id);const gallery=await sellerImages(item.buy,item.image);item.images=gallery.images;item.galleryStatus=gallery.galleryStatus;item.image=item.images[0];return json(item)}catch(e){console.error('detail upstream:',e?.name,e?.message);return json({error:'Source unavailable'},502)}}
return new Response('Not found',{status:404})}};
